import "./globals.css";
import { MyContextProvider } from "../context/MyContext";

export const metadata = {
  title: "RAINBOWROADS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Kode+Mono:wght@400..700&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        <MyContextProvider>{children}</MyContextProvider>
      </body>
    </html>
  );
}
